version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:13
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_DATABASE: otus-highload-homework
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
